### ISSUE TITLE
Wikidata URIs

### ISSUE THREAD

**Issue by Tpt** [philbarker/wdtax#1]
Thank you for this great project! Just a detail about Wikidata items URIs: they follow the pattern "http://www.wikidata.org/entity/QXXX" (i.e. with http and not https). See: https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format

**Comment by philbarker** [comment]
Thank you. @tpt I love issues that can be fixed by deleting one character.
